# Generated by Django 5.2.4 on 2025-08-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduzone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('rating', models.IntegerField(max_length=5)),
                ('image', models.ImageField(upload_to='Pagecourses/')),
            ],
        ),
    ]
