# Generated by Django 5.2.8 on 2026-01-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduzone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecourse',
            name='image',
            field=models.CharField(help_text="Path to image in static folder, e.g., 'images/courses/python.png'", max_length=255),
        ),
    ]
