# Generated by Django 5.2.8 on 2026-01-03 13:03

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduzone', '0002_alter_pagecourse_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='content',
            field=ckeditor.fields.RichTextField(default='No content available for this course yet.'),
        ),
        migrations.AlterField(
            model_name='course',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
