# Generated by Django 5.2.4 on 2025-08-27 15:51

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduzone', '0002_pagecourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecourse',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='title', unique=True),
        ),
    ]
