# Generated by Django 5.2.8 on 2026-01-03 13:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduzone', '0003_course_content_alter_course_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='content',
        ),
        migrations.AlterField(
            model_name='pagecourse',
            name='content',
            field=ckeditor.fields.RichTextField(default='No content available for this course yet.'),
        ),
    ]
