# Generated by Django 5.2.4 on 2025-08-27 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduzone', '0003_pagecourse_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagecourse',
            name='slug',
        ),
    ]
