# Generated by Django 5.2.4 on 2025-09-11 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduzone', '0004_remove_pagecourse_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecourse',
            name='content',
            field=models.TextField(default='No content available for this courses yet.'),
        ),
    ]
