# Generated by Django 5.2.8 on 2026-01-07 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduzone', '0004_remove_course_content_alter_pagecourse_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.CharField(help_text="Path to image in static folder, e.g., 'images/courses/python.png'", max_length=255),
        ),
    ]
