# Generated by Django 5.2.8 on 2026-01-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduzone', '0006_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('bio', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='About',
        ),
    ]
